### ISSUE TITLE
Is anvil missing?

### ISSUE THREAD

**Issue by 0xsamgreen** [uniswapfoundation/scaffold-hook#33]
Hi, 

I'm working through the Getting Started guide. When I run `npm run anvil` I get this:

```
% npm run anvil
npm ERR! Missing script: "anvil"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

% npm run
Lifecycle scripts included in @se-2/nextjs@0.1.0:
  start
    next dev

available via `npm run-script`:
  dev
    next dev
  build
    next build
  serve
    next start
  lint
    next lint
  format
    prettier --write . '!(node_modules|.next|contracts)/**/*'
  check-types
    tsc --noEmit --incremental
  vercel
    vercel
  vercel:yolo
    vercel --build-env NEXT_PUBLIC_IGNORE_BUILD_ERROR=true
  wagmi
    wagmi generate
```
Note that I have Foundry installed, and I have installed the anvil cargo into it. I can start `anvil` from the `nextjs` directory. Do I need to install an anvil plugin?

**Comment by saucepoint** [comment]
@0xsamgreen so `npm run anvil` and `npm run deploy:*` are available in the root of the repository (`scaffold-hook/`)

the other react commands (`npm run dev / npm run wagmi`) are available in the `nextjs/` directory

**Comment by saucepoint** [comment]
feel free to open or reach out to me on twitter if you're still having issues

**Comment by 0xsamgreen** [comment]
Got it. Thanks, @saucepoint!
